version: 2

sources:
  - name: airbyte_landing          # dit is de dbt "source name"
    database: horseflex-483119  # optioneel, maar ik raad aan: expliciet
    schema: airbyte_landing        # dit is je BigQuery dataset
    tables:
      - name: Webshop_export_orders  # dit is je BigQuery tabelnaam
      - name: Goedgepikt_reseller_orders  # dit is je BigQuery tabelnaam
      - name: Prijslijst  # dit is je BigQuery tabelnaam
      - name: Flexrexorders  # dit is je BigQuery tabelnaam

  - name: azure_landing
    database: dwh_horsefelx
    schema: dbo
    tables:
      - name: landing_flexrex_orders
      - name: landing_horseflex_Goedgepikt_reseller_orders
      - name: landing_horseflex_orders
      - name: landing_horseflex_products
      - name: landing_horseflex_customers


    